#
# Copyright (C) 2023 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/miatoll/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),miatoll)

endif